### ISSUE TITLE
feature - Player

### ISSUE THREAD

**Issue by kminsmin** [NBC-A03-Unity/FosterTheMonster#12]
### Issue 타입(하나 이상의 Issue 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 상세 내용

- [x] 플레이어 구조체(강인함, 체력, 포획한 몬스터 저장)
- [x] 몬스터 포획 처리
- [x] 강인함 UI

### 예상 소요 시간

- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [x] `2h`
- [ ] `2.5h`
- [ ] `3h`

**Comment by Munch310** [comment]
머지 완료.
