### ISSUE TITLE
feature-ResourceManager

### ISSUE THREAD

**Issue by kksoo0131** [NBC-A03-Unity/FosterTheMonster#45]
### Issue 타입(하나 이상의 Issue 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 1. ResourceManager를 추가하려고 한다.

-  어디서든 Resouce.Load를 사용해서 오브젝트를 Instatiate 할때 사용

- 지금 CardManager에서는 Resources.LoadAll로 모든 리소스들을 미리 불러와서 메모리에 저장해두고 사용한다.

- 그리고 CardManager는 Monobehaviour가 아닌 싱글톤으로 모든 씬에서 유지된다.

- 그렇기 떄문에 모든 리소스가 계속해서 메모리에 저장되어 있어야하고

- 이 방식으로 모든 리소스를 관리하게 되면 메모리에 너무 많은 리소스가 저장되어야 해서 문제가된다.

### 2. ResourceManager를 그래서 지연 로딩 방식으로 만들려고한다.

- 지연 로딩은 필요할 때 Resource를 Load 하고 사용하지 않을때 UnLoad 하는 방식이다.

### 3. ResourceManager 상세

- 각 리소스의 종류별로 Dictionary를 준비한다.

- 리소스를 호출할때 먼저 Dictionary에 해당 리소스가 있는지 확인한다. 없다면 Resouce.Load로 가져와서 Dictionary에 저장한다.

- Dictioanry를 전부 UnLoad시키는 기능을 만든다. (Scene을 넘어갈때 호출)

- 씬이 넘어갈때 모든 Dictionary를 UnLoad 시킨다.

>> 중복 로드 방지
>> 프리펩이 없다면 로드하고 이미 로드 되있다면 Dictionary에서 찾아서 리턴

### 예상 소요 시간

- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5h`
- [x] `3h`

**Comment by Munch310** [comment]
머지 완료.
