### ISSUE TITLE
feature-MonsterMovement

### ISSUE THREAD

**Issue by Zif1519** [NBC-A03-Unity/FosterTheMonster#5]
### Issue 타입(하나 이상의 Issue 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 상세 내용

- [x] 몬스터 데이터 관리용 SO 틀 잡기
- [x] 몬스터 클래스 틀 잡기
- [x] Raycast의 성능이슈 고민해보기
- [x] Raycast를 이용한 몬스터 이동범위 제한하는 방법 구현.

### 예상 소요 시간

- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5h`
- [x] `3h`

**Comment by Munch310** [comment]
머지 완료.
