### ISSUE TITLE
feature - DataManager

### ISSUE THREAD

**Issue by kksoo0131** [NBC-A03-Unity/FosterTheMonster#52]
### Issue 타입(하나 이상의 Issue 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 상세 내용

Scene을 이동해도 유지되어야 하는 유저의 현재 데이터들을 관리하는 매니저 클래스

### 예상 소요 시간

- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [x] `2h`
- [ ] `2.5h`
- [ ] `3h`

**Comment by Munch310** [comment]
머지 완료!
