### ISSUE TITLE
enhancement - CardManager

### ISSUE THREAD

**Issue by kksoo0131** [NBC-A03-Unity/FosterTheMonster#57]
### Issue 타입(하나 이상의 Issue 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 상세 내용

- [x] 카드를 생성할 때 등급에 따라서 생성할 수 있는 기능을 추가
- [x] 카드 데이터를 등급별로 나누어서 관리
- [x] 구조 개선

### 예상 소요 시간

- [ ] `0.5h`
- [x] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5h`
- [ ] `3h`

**Comment by Munch310** [comment]
머지 완료.
