### ISSUE TITLE
fix + feature - Map Generation

### ISSUE THREAD

**Issue by kminsmin** [NBC-A03-Unity/FosterTheMonster#59]
### Issue 타입(하나 이상의 Issue 타입을 선택해주세요)

- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 상세 내용

- [ ] 방 구멍 막기  
- [ ] 몬스터 스폰 포인트 저장할 배열 생성

### 예상 소요 시간

- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5h`
- [ ] `3h`

**Comment by Munch310** [comment]
머지 완료.
