### ISSUE TITLE
feature-PlayerController

### ISSUE THREAD

**Issue by kminsmin** [NBC-A03-Unity/FosterTheMonster#6]
### Issue 타입(하나 이상의 Issue 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 상세 내용

- [x] 인풋 시스템을 이용한 플레이어 조작  
- [x] 조작감 개선  

### 예상 소요 시간

- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [x] `2.5h`
- [ ] `3h`

**Comment by Munch310** [comment]
머지 완료.
