### ISSUE TITLE
enhancement - CardUI

### ISSUE THREAD

**Issue by kksoo0131** [NBC-A03-Unity/FosterTheMonster#70]
### Issue 타입(하나 이상의 Issue 타입을 선택해주세요)

- [ ] 기능 추가
- [ ] 기능 삭제
- [x] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 상세 내용

CardSystem 과 UI 연결부분에 임시로 작성했던 코드들 수정

### 예상 소요 시간

- [ ] `0.5h`
- [x] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5h`
- [ ] `3h`

**Comment by Munch310** [comment]
머지 완료.
